### adapted from prediXcan_script_metaA_v7.R

library(RSQLite)
setwd('/Users/Administrator/Downloads/YZ-20191122T154314Z-001/YZ')

### step 1: read in predicted expression file
### generated by PrediXcan, includes all genes

pred_expr_all <- read.table("frontal_cortex_predicted_expression.txt",header=T,stringsAsFactors=F)
pred_expr_all[pred_expr_all==NaN] <- NA

### step 2: read in gene list

gene_list_all <- read.csv("DLPFC_gene_list.csv",header=T,stringsAsFactors=F)

### step 3: read in extra attributes file
### downloaded from PredictDB, tissue-specific

sqlite <- dbDriver("SQLite")
dbname <- "gtex_v7_Brain_Frontal_Cortex_BA9_imputed_europeans_tw_0.5_signif.db"
db = dbConnect(sqlite,dbname)
extra_attr <- dbReadTable(db,"extra")

### step 4: subset by genes with successfully predicted expression levels
### removing NAN genes and removing those that are not present in both lists 
### list one is weights, list 2 is imputed expression levels of genes confident in imputing reliably 

gene_list_short <- merge(gene_list_all,extra_attr,by.x='SYMBOL',by.y='genename')
pred_expr_short <- pred_expr_all[,names(pred_expr_all) %in% gene_list_short$gene]

### step 5: scale predicted expression values and add IIDs 

pred_expr_scaled <- as.data.frame(apply(pred_expr_short,2,function(x){scale(x)}))
row.names(pred_expr_scaled) <- as.character(pred_expr_all$IID)

### step 6: replace ENS IDs with gene names
### if order remains consistent, sum (line 36) will equal number of genes

short_gene_names <- data.frame("gene"=names(pred_expr_scaled))
short_gene_names <- merge(short_gene_names,gene_list_short,by='gene')
sum(names(pred_expr_scaled)==short_gene_names$gene) 
names(pred_expr_scaled) <- short_gene_names$SYMBOL

### step 7: get effect weights

gene_expr_weights_M <- short_gene_names$MD2_DLPFC_M.1
gene_expr_weights_F <- short_gene_names$MD2_DLPFC_F.1

gene_expr_binary_M <- gene_expr_weights_M 
gene_expr_binary_M[gene_expr_binary_M<0] <- -1
gene_expr_binary_M[gene_expr_binary_M>0] <- 1

gene_expr_binary_F <- gene_expr_weights_F 
gene_expr_binary_F[gene_expr_binary_F<0] <- -1
gene_expr_binary_F[gene_expr_binary_F>0] <- 1

### step 8: compute scores

scores <- data.frame("male.weighted"=numeric(nrow(pred_expr_all)),"female.weighted"=numeric(nrow(pred_expr_all)),
                     "male.unweighted"=numeric(nrow(pred_expr_all)),"female.unweighted"=numeric(nrow(pred_expr_all)))

for (i in 1:nrow(pred_expr_all)){
  scores[i,1]<-sum(pred_expr_scaled[i,]*gene_expr_weights_M,na.rm=T)
  scores[i,2]<-sum(pred_expr_scaled[i,]*gene_expr_weights_F,na.rm=T)
 # scores[i,3]<-sum(pred_expr_scaled[i,]*gene_expr_binary_M,na.rm=T)
 # scores[i,4]<-sum(pred_expr_scaled[i,]*gene_expr_binary_F,na.rm=T)
}

scores <- round(scores,1)
scores$IID <- pred_expr_all$IID
scores <- scores[,c(5,1:2)]
write.csv(scores,'scores_frontal_cortex_predicted_expression.csv')